version: "3.7"
services:
  web:
    image: webdevops/php-nginx
    ports:
      - "8880:80"
    restart: always
    hostname: "webtest"
    #privileged: true
    environment:
      TZ: "Asia/Bangkok"
      PHP_UPLOAD_MAX_FILESIZE: 500m
      PHP_POST_MAX_SIZE: 500m
      FPM_PM_MAX_CHILDREN: 100
      FPM_PM_START_SERVERS: 50
      FPM_PM_MIN_SPARE_SERVERS: 25
      FPM_PM_MAX_SPARE_SERVERS: 100
      FPM_PROCESS_IDLE_TIMEOUT: 10s
      fpm.pool.listen: 0.0.0.0:9000
      fpm.pool.pm.status_path: /status.php  
      WEB_DOCUMENT_ROOT: /app/html
    volumes:
      - ./:/app
    command: [ "bash", "-c", "cd /app && composer update" ]