project:
  name: demo-php-ci
  # env: dev
  project_lang: php
  lang_ver: 7.2
  user: Airl3uZ
  repo: demo-php-ci
  branch: citest
  localPath: data
  scm: github
  steps:
    - checkout
    - unittest
    - sonarscan
    - webscan
    - owasp