project:
  name: demo-php-ci
  env: dev
  project_lang: php
  lang_ver: 7.2
  gitUrl: https://github.com/Airl3uZ
  repo: demo-php-ci
  branch: citest
  localPath: data/app
  scm: github
  test:
    - unittest
    - sonarscan
    - webscan
    - owasp